name: Ubuntu slim system information
on:
  workflow_dispatch:
    inputs:
      use-prerelease:
        default: false
        type: 'boolean'
        required: false

jobs:
  download-and-run:
    name: setup and run
    runs-on: ubuntu-slim
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Setup Fastfetch
        uses: ./.github/workflows/fastfetch-base/ubuntu
        with:
          use-prerelease: ${{ github.event.inputs.use-prerelease }}
      - name: Setup Inxi
        uses: ./.github/workflows/inxi-base/ubuntu
      - name: Run Fastfetch
        run: fastfetch -c all
      - name: Run Inxi (as root)
        run: sudo inxi -FxxxZ
      - name: Print environment variables (printenv)
        run: printenv
      - name: Print environment variables (set)
        run: set
      - name: Print environment variables (export)
        run: export